blank_issues_enabled: true
contact_links:
  - name: Fusion README
    url: https://github.com/junyoung090928/Fusion
    about: Please check the README for basic usage, build instructions, and project information.
